# action.yml
name: 'Rafay CLI Setup'
description: 'Downloads and configures Rafacy rctl CLI'

runs:
  using: "composite"
  steps:
    - name: Run setup script file
      run: |
         chmod +x $GITHUB_ACTION_PATH/rctl_setup.sh
         $GITHUB_ACTION_PATH/rctl_setup.sh
      shell: bash
